### ISSUE TITLE
Improve logging/error handling for Java/.NET services

### ISSUE THREAD

**Issue by ammerzon** [dynatrace-oss/unguard#20]
**Is your feature request related to a problem? Please describe.**

- Most of the logging doesn't print any timestamps or affected line numbers.
- Frontend logging is too verbose in error cases

## Definition of Done

- [ ] A proper logging framework for all services is used
- [ ] The logs are consistent across services and contain timestamps and class/code location if possible
- [ ] The console is not spammed when errors are thrown

## Tasks

- [ ] Try out unguard under normal load and observe logs (to spot spam/bad logs)
- [ ] Adjust logs of the microblog-service
  - Java, SL4J 
- [ ] Adjust logs of proxy-service
  - Java, Log4J (don't change that) 
- [ ] Adjust logs to ad-service
  - .NET, add a framework. If not included, look up best practices 
- [ ] Ensure quality and functionality
  - Manual tryout, tests, warnings, code-style 

## Additional context

- The frontend tends to spam unreadable loglines when other services crash/are not available
- Stick to logging format already present in e.g microblog-service
