### ISSUE TITLE
Find convenient way to handle the .idea folder

### ISSUE THREAD

**Issue by ammerzon** [dynatrace-oss/unguard#24]
Right now, the name of the JVM is hardcoded in the [Gradle file](https://github.com/dynatrace-oss/unguard/blob/master/.idea/gradle.xml#L11), which is a problem if your JVM in IntelliJ has a different name.
Additionally, changes to the JVM / project structure are picked up as version control changes, which we want to avoid.

## Definition of Done

- [ ] The project can be imported into any JetBrains IDE regardless of the installed JVM name
- [ ] The Jetbrains IDE support is OS independent
- [ ] Changes to the project structure are not tracked in the version control

## Tasks

- [ ] Find a feasible solution
- [ ] Sync with the project maintainers about the proposed solution
- [ ] Implement the accepted solution
- [ ] Document solution ([DEV-GUIDE.md](https://github.com/dynatrace-oss/unguard/blob/master/docs/DEV-GUIDE.md))
- [ ] Test solution on different operating systems

## Additional context

- Possible idea would be a script that creates the .idea contents
- Think about how to do it - should we use Gradle, Bash / CMD?
- https://youtrack.jetbrains.com/issue/IDEA-276735
