### ISSUE TITLE
Dynamically use helm release-name for Kubernetes resources

### ISSUE THREAD

**Issue by MfCrizz** [dynatrace-oss/unguard#50]
Currently "unguard" is hard coded in many parts of the helm chart. 

Use the helm release-name instead. 
The helm release name can be referenced in the chart using the function `{{- include "unguard.fullname" -}}`
If ungaurd services (e.g. envoy-proxy) also use a hard-coded name, update service to specify the name via an environment variable. 

## Definition of Done
- [ ] All Kubernetes resources and application services use the helm release-name.

## Tasks
- [ ] Update the Chart to use the helm release-name
- [ ]  Update ungaurd services to use the helm release-name
